### ISSUE TITLE
replace jiffy with jsone

### ISSUE THREAD

**Issue by velimir** [alertlogic/erllambda#52]
It's advised to build a package using erllambda contianer since the library depends on `jiffy`, that can't be loaded in AWS Lambda container if it was built on a different platform.

To make packetization easier how about we change json library to something that is erlang native like `jsone`?

**Comment by motobob** [comment]
how does this help other top level apps which have other miriad of native code? answer - it does not.:)

i'm not opposed to change of jiffy to jsonE as some day i want the same for erlcloud.

**Comment by velimir** [comment]
It does not though it does help other aws lambda functions which most likely do not have NIF/Port dependencies.
It's better to have this option rather than exclude it completely by using `jiffy` in a base library.

The other option would be to make JSON serialisation to be configurable/pluggable.
Can be inspired by `erlang-jose`:
https://github.com/potatosalad/erlang-jose/blob/f8f97fb651202386c951fccfcb61d123518ba05f/src/jose.erl#L71-L83
