### ISSUE TITLE
pthread error during thaw phase of Erlang VM

### ISSUE THREAD

**Issue by rmpalomino** [alertlogic/erllambda#71]
As mentioned in #68, there is a persistent pthread error that causes a crash of the Erlang VM in long running AWS Lambda functions. This was noticed in a Lambda function that processes a steady AWS Kinesis stream.

I have opened this issue after #68 was resolved, because this underlying issue is not fixed; #69 only prevents the resulting Linux core dumps from filling disk space, it does not prevent the Erlang VM from crashing during the AWS Lambda thaw phase and causing a core dump.

The pthread error shown in #68 is:
```
pthread/ethr_event.c:164: Fatal error in wait__(): Operation not permitted (1)
```

Also see the error and additional discussion in https://github.com/leo-project/leofs/issues/843#issuecomment-331588498:
```
Sep 20 18:55:53 bodies-master leo_manager[406]: pthread/ethr_event.c:164: Fatal error in wait__(): Invalid argument (22)
```

**Comment by motobob** [comment]
move to provided.al2 AMI and the issue will go away

**Comment by velimir** [comment]
It is assumed to be addressed by https://github.com/alertlogic/erllambda/issues/79

**Comment by motobob** [comment]
yes @velimir we've already moved it real deployments (actually time to move to `provided.al2.2022`) so #79 is to move the default and templates to latest.
